import helper

def main():


# here in the s you can add whatever you want ,can it also be an underscore
#
# It's a widely accepted practice in Python to use _ as a placeholder when the variable's value is not relevant to the current context.
    for s in range(5):
#It iterates through the range of numbers generated by range(5), but the actual value of _ in each iteration is not needed or use
        #
        #
        random_ad = helper.get_random_ad()
        random_ad.display()

if __name__ == "__main__":
    main()